language: emacs-lisp
env:
  matrix:
    - TAG=24.5-dev
    - TAG=27.1-dev
before_install:
  - docker-compose config
  - docker-compose pull
script: docker-compose run --rm emacs_test bash -c 'cd /init-loader && make test'
